apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - cert-manager
  - longhorn
  - monitoring
  - cloudnative-pg
  - dragonfly
  - reloader
  - spegel
  - garage
  - loki
  - trivy-operator
  - kyverno
  - traefik
