apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-api
  - cilium
  - cert-manager
  - longhorn
  - monitoring
  - cloudnative-pg
  - valkey
  - reloader
  - spegel
  - loki
  - tempo
  - trivy-operator
  - kyverno
  - kyverno-policies
  - intel-gpu-plugin
