apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-outpost
  namespace: authentik
data:
  outpost.yaml: |
    version: 1
    metadata:
      name: Homelab Outpost Config
    entries: []
