apiVersion: v1
kind: Secret
metadata:
  name: garage-secrets
  namespace: garage
stringData:
  rpc-secret: ENC[AES256_GCM,data:E+6BqRUygH4bRJbPkopyKFIh0Xtd6iZsEzrV3lAae7SdicnAxQ5//m7UG6vdcEpP/aOASuwSTQnAmzCJb3x0WQ==,iv:o/iLWyq6cK5rUfIMAebwKXUejmKYS2iz6z7CFDbfbL8=,tag:lg/Zk0Hb16/yrwyzaxjlgA==,type:str]
  admin-token: ENC[AES256_GCM,data:TXKTnX5ex/56R2CVL2Za4e6G4NdK8ULUQMtw8CZ5QKk=,iv:tWi7SZY0r/zZGSy/RU7VN1ZcWXrxku9FdxuDMT88zFQ=,tag:2roFtZXdi8PFzJ+KY1w0tg==,type:str]
  metrics-token: ENC[AES256_GCM,data:SCyyl1Sr9coMTyCdV3NxrFAWZQSkNFxm5msde4LsB24=,iv:jGQi+HpzKliTIyf8pzCD7FJ4tPywhMBLIevgqSdZCEk=,tag:HETJhF/CPIvhwOXu2ZmTng==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQU5GNGtiSzIvSEZwbXl6
        V21QMFFMbnkxSlBwYjBHbkxvU2tGUlJDNGxzCldFdmNHZmx0RTAzYlQza2dEWVJD
        MjRKbWRhYjFuZHJtVk9sblJBMHdVN00KLS0tIEt1dVYwNGcxSnloOXRPN3BNRkdt
        OExLZFl4Rnk4am0xeUgyeEg4NTJ5UzgK5dPu5hsFBKkzDfRQCMfFod88MaHzEqIO
        HTmQ0ewxPDR5M5x1qbDPYtrYeah6a3bCuZdk525R1I45g5k3RwnpPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T11:23:08Z"
  mac: ENC[AES256_GCM,data:tcxxhTiz3EGa1j4BOhRs4TNMMVoO7rqEjWB1eryHvu4a7frFfLuoId4NK/xbbtQQNcAb93lM4PkQQ46x1IMjZkCvHwm3zvYlMSt1kLEgpjlsXp6JaTZ9609WFEDFe9HHUiI6XkzvcxVFHhAUbFY16jsZZf7zYCTXPIRDKTXygsM=,iv:jni562fAbvV1tu5BtpCLw94h88zbzjH4cKDKvzU8QOM=,tag:Yi1ed5p+0wqFimSWAulzXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
