apiVersion: v1
kind: Secret
metadata:
  name: homarr-secrets
  namespace: homarr
type: Opaque
stringData:
  SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:TWAlqu10H90E3tGdf8o7rgTDyt3KEkWnLC8DBAc1k7pcsZKNx1eIY1vm+nOBF2o+x34nbb5yYCmYiRnIeHi5Pg==,iv:bmYHYkTYFkGUXmyeJCuDJJlHr3QyRv4/J8xLvcGz1KY=,tag:GoQCaupey8RdV3mn/reOQA==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdVZWcG9iUzFIOXA3TXZ6
        di9QZWJCcDd2VUNlUjlDWlFiYjMveEhwK0hBCmhNNTBZYkd1bWZYNVYwbmRBT1pL
        cVZ3dGgxNGRyZU1MRHpwUG0xdTNNdjAKLS0tIFhnZFJnbFFNZzZIbHFsZ0xBRHBa
        RmdTUVlHVWw5L0RMMFdMYXNJTXhnajAKfiBa6noHYGfLOExU/loKoyuP36d5Ljrc
        RQBEFiecoTSTw3NkA09uO1QYghIjSW3CSbirt3BGubmMNl+2Te64Mw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T15:34:52Z"
  mac: ENC[AES256_GCM,data:QWWA4niqb4C99mLM2MHo7E+qiHR2FMjP/imj8tc+wpJIxbCzQY6eS3F4ETEQs248iHAlmIIVhGiQKMnPHTMbibwNQuX+x97n0POEgValK3My7gJSPa9Bw4m85FKq2vD/KqSb9AX4Hxk3FoVYAhIePqqDicW4okYl4ValyzwiG4g=,iv:uIbV0Zz38notcAXx+9Pa/pBsNOpcxSM29UYLCF4K//Q=,tag:pP6cLztebKIb3zWFBj4GMA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
