apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: authentik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.${CLUSTER_DOMAIN}`)
      kind: Rule
      middlewares:
        - name: rate-limit
          namespace: traefik
        - name: secure-headers
          namespace: traefik
        - name: authentik-headers
          namespace: authentik
      services:
        - name: authentik-server
          port: 80
  tls:
    secretName: authentik-tls
