apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.sops.yaml
  - objectstore.yaml
  - postgres-cluster.yaml
  - scheduled-backup.yaml
  - helmrelease.yaml
  - certificate.yaml
  - ingressroute.yaml
  - resources/middleware.yaml
  - resources/outpost-route.yaml
  - blueprints/
  - pdb.yaml
  - network-policies.yaml
