apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.sops.yaml
  - postgres-cluster.yaml
  - helmrelease.yaml
  - certificate.yaml
  - httproute.yaml
  - reference-grant.yaml
  - blueprints/
  - pdb.yaml
  - network-policies.yaml
