---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: authentik-s3-store
  namespace: authentik
spec:
  configuration:
    destinationPath: s3://cnpg-backups/authentik
    endpointURL: http://s3.garage.local:3900
    s3Credentials:
      accessKeyId:
        name: cnpg-s3-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-s3-credentials
        key: ACCESS_SECRET_KEY
      region:
        name: cnpg-s3-credentials
        key: AWS_DEFAULT_REGION
    wal:
      compression: gzip
  retentionPolicy: "30d"
