apiVersion: v1
kind: Secret
metadata:
  name: cnpg-s3-credentials
  namespace: authentik
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:xHhRDGsUHHxCutHfoSZwxpX5moLBWe5Db7o=,iv:5rKHyj3Y8zzh21t7glA2iUM/nQ2DIqyOgAMqgtmn5Fw=,tag:Puc+wjErn/rElRyZMO5ajg==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Dh+CELhgEM69Ux2WKf9lygqYZiLJlwn0KtZ4ZKB12pPLgRtDD3XwLPnGRRQBDUPbcA4ecxubtC+v59uI7V+OyA==,iv:JOsIvvk9LVv1QknNM4TSpFxFTmhzaBPgxTx3DeIEy6U=,tag:5/M2+tAJjeY1w6RZS3YeHA==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dS9BazlTM1RjOVo0TFRG
        aWhYMlJTWG90MmxxV25NOXVUN0J6STdKd1JvCnJDU1JVSHR4dmMwNWlYSWdwd1dy
        NTJTbUE4MDAvbDl0MTFtRVRWMnAyNWsKLS0tIGo4UWdzOTZQN2lad0RCWUhjSkEw
        UDZBUmJsY2xBdkxnTTZSK0Z2WHN3b3cKwYJeO6a4Vg1kvmOt2Hnc2e6ZBtc/zd5l
        BuWud0r1eteIsWinY/q/3/yR84f6hhjhX8VvJqXKyPiDgM17ESYKAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T13:07:16Z"
  mac: ENC[AES256_GCM,data:xsWyPNqanVDryW9dLhQh0gAC1lqDimvPwT01ma6xtlMffbi+G4UNoDTH0GN+EK0hRfgZbtprLx71UYZihIWwokTYDOROImh3n/Oj2JWUYlUghcvrLWwTGGL3Uz0T+ALcJHP72cSge5PJ2U59fUIqDz7FkINBrnLEmN54qz8ajS8=,iv:noh/meMFdpbrIGVO4hQUOgu/Aq5yT9W1vfWENI8ncv0=,tag:+LYlhiQ0JpdrWYGAG8A52g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
