---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-postgres-backup
  namespace: authentik
spec:
  schedule: "0 */6 * * *" # Every 6 hours
  backupOwnerReference: self
  cluster:
    name: authentik-postgres
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: authentik-s3-store
  immediate: true
