apiVersion: v1
kind: Secret
metadata:
  name: authentik-postgres-credentials
  namespace: authentik
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:zlpHfuIM1fXa,iv:mrrsbLR6Xv9Q7WQOqo3D/klhG5CXwTMwa0eEIr3HNFA=,tag:84f5Eu6nuUvoZG3CGRCNzw==,type:str]
  password: ENC[AES256_GCM,data:nNWkSGtSJyvwX2CzL3ntVucYfK9YrRbsIuvo0Cz26ikGJjAIwyE4koxDMJI=,iv:ZoWn0FLS5W0WGq+x5Xx1r0qRCg8YiKyhXU1nT7SjTLk=,tag:utlEHREvB5g9P8K/vh+yGQ==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UzVpa0dEWTFTQlByZVNw
        VUpsdmpac0hUa0lreUJnQXcvZU5FTlNqWkhVClZ2YnBXc05MZVF0TGF4U0lQVGpv
        eE5oT3U5S0hrY1owZmQxUFFFckVHU28KLS0tIGpnZndtQnZ0Y016b24rMEtEQVpR
        SnRhK2xpcUVoNjVlUFl1b3YxTC9YeTQKB54d8V0dG4KHJvTWoPXrqpY7GbEa3mvS
        rhCISPfyreH3m8OhTAi3vnWxHQ5j6HTzBL0JEqQAb71wsXQ5ud7djw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T23:20:25Z"
  mac: ENC[AES256_GCM,data:FH5wf31DEEbdSyFKHCx8KG15CXHd32JEtrHj0JvHAE0xJ2qEXmveY5AlsiXht1amOhDoolyvgw0mw1OBEAvleMkbMLbBiGYeBOFqfyJgsMQk/1KxgzrkQnvHxrHsAa/GcJLuE9Eh7bnUgsKOX7ACJJo4WClWs7zwirP6XjQYvjA=,iv:FfsTTB+LhK3LbyLrjJyr3zhom6ScnVayMSvoDWsR+L4=,tag:1cUq3LY81JHPSGIY/QDOlw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: authentik
stringData:
  secret_key: ENC[AES256_GCM,data:FPeIyEF6Z5FeYBbS30JHrMW90ogKxSGl6KPh3NExMxEOUoFtgHQmzq4/VCq59fEsw/T5JrQi7eJJcwo638Rh4g==,iv:0NYo4URUil240UWL1WMIUiursHjPu0h30txaNGWpj8A=,tag:t5NHb8BmiD3M6/ql6+4qEg==,type:str]
  grafana_client_secret: ENC[AES256_GCM,data:SLG579yrofR1RJQ1LinTcDIl8tsIBI6+NTnHz4CWODA=,iv:JsQWR+Rvhu/pJ34Nndu/ImuaEmFw0dCWEe60ZglDBg4=,tag:qDeDWsRmf82EbqKfXV/KHA==,type:str]
  ha_client_secret: ENC[AES256_GCM,data:QizdhG+jMT1Zic9h5YgWdFM+tc/KYVlpM6gzNqanoF/f2lhajU8JaMff5w==,iv:zd5eNtU2YNTKfK/DivNeerGWP6nrAcPwjh5Gj205hwM=,tag:H63oZV4h984vWjvmv/YAhg==,type:str]
  homarr_client_secret: ENC[AES256_GCM,data:tQvSBISm7fRZ9aFRHE4SKVeLTZBXsx6uyQUhVRpucKVac99HSbYoNvrOP2iIcBvXwbjVKyEkctF2VIbev7X/Bw==,iv:wrCPEg7QsODtxrPLrj04WWpYEj0Vu6kE3JODBiyXggU=,tag:Zj9nmPoPWar+LX9fpxi6wg==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UzVpa0dEWTFTQlByZVNw
        VUpsdmpac0hUa0lreUJnQXcvZU5FTlNqWkhVClZ2YnBXc05MZVF0TGF4U0lQVGpv
        eE5oT3U5S0hrY1owZmQxUFFFckVHU28KLS0tIGpnZndtQnZ0Y016b24rMEtEQVpR
        SnRhK2xpcUVoNjVlUFl1b3YxTC9YeTQKB54d8V0dG4KHJvTWoPXrqpY7GbEa3mvS
        rhCISPfyreH3m8OhTAi3vnWxHQ5j6HTzBL0JEqQAb71wsXQ5ud7djw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T23:20:25Z"
  mac: ENC[AES256_GCM,data:FH5wf31DEEbdSyFKHCx8KG15CXHd32JEtrHj0JvHAE0xJ2qEXmveY5AlsiXht1amOhDoolyvgw0mw1OBEAvleMkbMLbBiGYeBOFqfyJgsMQk/1KxgzrkQnvHxrHsAa/GcJLuE9Eh7bnUgsKOX7ACJJo4WClWs7zwirP6XjQYvjA=,iv:FfsTTB+LhK3LbyLrjJyr3zhom6ScnVayMSvoDWsR+L4=,tag:1cUq3LY81JHPSGIY/QDOlw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
