apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgres-credentials
    namespace: authentik
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:vmdAyfbtf3Me,iv:9HDVE3gfY3kZ9yoY4HLILJ401fKRZdCeuiuxhyldn1c=,tag:YmwQbsjAe4uJrklS02Ri4Q==,type:str]
    password: ENC[AES256_GCM,data:m16v7qj5eTQlY2N0cJNKN/fvDvrY0xQziPJPhqzvQP1PWGlSaC/+JL+xon0=,iv:IOYhOl4M/AWqKvD8woLwriVt3cVYdeKGufCt+QU1Ui4=,tag:L2LTQhJQHPhYC5QovK2G5w==,type:str]
sops:
    age:
        - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdDlvemFraHdaMjB2aDhF
            UVFwRFdZUTVXRDRaWGUvWndPZTQ4ZjN2N2xVCjdUMCtsVUxqWTRLQ0tvbUU4eXhY
            MVFSUFUvbkxRaTBmY1lXK2RKekNyUkUKLS0tIGZMV1BtdElJYU9ySy90aWMxVzEz
            VUJsRjl2b2lvQ1VpM21qY3VJYTJYcXMKvls3u697OjLVp+gIT8LfGNXLAezfVveW
            0dw/QJLUSxA/viw6NJy3HF5WPRDl/ybm24j3fXNX+NScbr21TszqOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T14:10:20Z"
    mac: ENC[AES256_GCM,data:Pqh+wAkHtl642wHwj99VNZDt3eNeRPH44wqsStXvuMpaCfdJMQByu6uNqoGwqgMUsmEjUaiSELxWW8yxEBALdSQp1Mf1rxDPJOdUZXPTIDggtIDnyKETXHPIXrKzdGtw4kf7P6eNXuCM+EYs9hzNlCL/mXh58laCmO6pFjopVyE=,iv:piMFLm3QWZcll5gM4FdIIEVbtgB2DRFWXkBIUXAJs4c=,tag:dhuf2Mssq778XyDwaMgJ4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
stringData:
    secret_key: ENC[AES256_GCM,data:8De5NLIVwXXfCGH/tY3Xz/4h7g+qJR/vBqC3tkdtr9NahTWmimC2QWfqIxeah8/yghvIlj4oPWaYq+hkV5hGXA==,iv:wgUyjrZIi7IUInTVn2LVUbknRXH5E8tBl+GdFuLtiPw=,tag:9kkUJeKlFvKU2OL8nLqW+A==,type:str]
sops:
    age:
        - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdDlvemFraHdaMjB2aDhF
            UVFwRFdZUTVXRDRaWGUvWndPZTQ4ZjN2N2xVCjdUMCtsVUxqWTRLQ0tvbUU4eXhY
            MVFSUFUvbkxRaTBmY1lXK2RKekNyUkUKLS0tIGZMV1BtdElJYU9ySy90aWMxVzEz
            VUJsRjl2b2lvQ1VpM21qY3VJYTJYcXMKvls3u697OjLVp+gIT8LfGNXLAezfVveW
            0dw/QJLUSxA/viw6NJy3HF5WPRDl/ybm24j3fXNX+NScbr21TszqOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T14:10:20Z"
    mac: ENC[AES256_GCM,data:Pqh+wAkHtl642wHwj99VNZDt3eNeRPH44wqsStXvuMpaCfdJMQByu6uNqoGwqgMUsmEjUaiSELxWW8yxEBALdSQp1Mf1rxDPJOdUZXPTIDggtIDnyKETXHPIXrKzdGtw4kf7P6eNXuCM+EYs9hzNlCL/mXh58laCmO6pFjopVyE=,iv:piMFLm3QWZcll5gM4FdIIEVbtgB2DRFWXkBIUXAJs4c=,tag:dhuf2Mssq778XyDwaMgJ4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
