apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - disallow-latest-tag.yaml
  - require-resource-limits.yaml
  - disallow-privilege-escalation.yaml
  - restrict-registries.yaml
