apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-tls
  namespace: unifi
spec:
  secretName: unifi-tls
  issuerRef:
    name: ${CLUSTER_ISSUER}
    kind: ClusterIssuer
  dnsNames:
    - unifi.${CLUSTER_DOMAIN}
