apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - unifi-secrets.sops.yaml
  - mongodb-init.yaml
  - unifi.yaml
  - network-policies.yaml
  - certificate.yaml
  - httproute.yaml
  - reference-grant.yaml
  - pdb.yaml
