apiVersion: v1
kind: Secret
metadata:
  name: unifi-secrets
  namespace: unifi
type: Opaque
stringData:
  MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:uRkUMNuYpkhBnqjBe0qx5Ng/K5sy8zsjYAUBD2AW2hE=,iv:khUtkRz5f7JKvDRLkLJa8Y8+GcEAlFeET1NmGhuFevw=,tag:+Oj7IPnS7iMqrrnQfxctvA==,type:str]
  MONGO_PASS: ENC[AES256_GCM,data:dXvEDceZmE02jqjwwGWjj4KI0G1u6c4RRyQjNAdjD3A=,iv:qmMkmJeYwBbM6x3XYRooY5rEgrMo+OuSGVRxm3Iwy6I=,tag:vkQg1tQUCvmFQprdW1ol9w==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITW9pR2pDWEd4eWxNVWky
        UTJMZFpTcTdmZFIyWmJ3ajRmdkQ5Z1gwQ2xvClpzU3JmYlRaK3JpdFNsaEJPZnA3
        VkN2Z3lwZjJtS1BlQUNjdmc4VzBGYVUKLS0tIFI3aTBJd0tTSjBpaEI3MzR3dlk2
        Qk1nZURiQkZObG1zUFZUQW1nV3dhV1kKAgMsQ12GYFXEn3AkSQj2OpZ5eLWpxOa9
        xt+DJtxOX99WoZr2qlBHcj5mmdiRsYncdhT2LMmzKplKFIYrPljZRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T00:49:50Z"
  mac: ENC[AES256_GCM,data:wJbvDrfbzGLXXjOUlouNsyXqpqcrfZiSM8pZTblu4b9HaUp3+g41w50wH/OWBX2KIzT7qWCuJn8IBRm6nmQp6194WUOLWLf2GLgTEgyF8n2kD+/6OJeHUoFVf3BGkNXilOkRKHCW8rwHBFdYGbCh+WnDFQJDMnvCfyGnhbe/8kw=,iv:fNy1UaR1aaJoEJSPt8E8avnnh5UJrshNjD7LAQpcu+w=,tag:onufjAzWTD+YfF3s+/iguQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
