apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-outpost
  namespace: authentik
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      priority: 15
      middlewares:
        - name: https-scheme
          namespace: authentik
      services:
        - name: authentik-server
          port: 80
  tls:
    secretName: authentik-tls
