apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: outpost-headers
  namespace: authentik
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "auth.${CLUSTER_DOMAIN}"
      X-Forwarded-Port: "443"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-outpost
  namespace: authentik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.${CLUSTER_DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      priority: 15
      middlewares:
        - name: outpost-headers
          namespace: authentik
      services:
        - name: authentik-server
          port: 80
  tls:
    secretName: authentik-tls
