apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frigate-tls
  namespace: home-automation
spec:
  secretName: frigate-tls
  issuerRef:
    name: ${CLUSTER_ISSUER}
    kind: ClusterIssuer
  dnsNames:
    - frigate.${CLUSTER_DOMAIN}
