apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-tls
  namespace: home-automation
spec:
  secretName: home-assistant-tls
  issuerRef:
    name: ${CLUSTER_ISSUER}
    kind: ClusterIssuer
  dnsNames:
    - home-assistant.${CLUSTER_DOMAIN}
