apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mosquitto.yaml
  - frigate-helmrelease.yaml
  - certificate.yaml
  - httproute.yaml
  - reference-grant.yaml
  - network-policies.yaml
