apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mosquitto.yaml
  - frigate-helmrelease.yaml
  - home-assistant-helmrelease.yaml
  - certificate.yaml
  - home-assistant-certificate.yaml
  - httproute.yaml
  - home-assistant-httproute.yaml
  - reference-grant.yaml
  - network-policies.yaml
  - mosquitto-pdb.yaml
  - frigate-pdb.yaml
  - home-assistant-pdb.yaml
