apiVersion: v1
kind: Secret
metadata:
    name: adguard-config
    namespace: adguard
stringData:
    AdGuardHome.yaml: ENC[AES256_GCM,data:5hzwO/BO1c/Vra/Cyq8WripLA4iVyStIIY2RVgUIj2vjdq/riKEo/c8QsfaELxWueowymw+ttyqeDvz7bQ6S8p3DbxcDVDXixhCPKB1N1SsbWxJ4mdr+iOP70C08hWEP8k0yTjLR76/pITZYTiuwjHrP3VU4D2IpyUp+9ga0LwVLIKB4WDPOErxQdxekQmZafyq2uleIfwEMHGxKS7kZZihihoGeK2d+Z9x1o6XW5/NrrGwNR98+JnZLHRHaykh9/cqzLXqwq6wio0GzFepvNBiadG+x0Nx4nBINKBUV84ZEiZ456RybunIDGZv7Zgh7jSL7Aw67bI6CkM6MOiDby/Jq3daJQPDAKISpIpCXlaRskcbUjtMDq4y6agxcPUIyemsY15iUlxCTl0HLc4Rdy6btJg+phsKl9/pCz72nZKiL7SZSaKgUKGm8jdNpw3dziG9nh2BKzJBHuk1T9ky+ScIbipcxeVGaxIJCU9BKSiMuAEaT3C9ePYpYAwdL+SrgZ8v5PpBIXREgIhzIaDR+864X7O7HyMowhAkCRpLy5gY34tr913bBtVXn524MzDDeZ23y0MN11R7XfkR2ZlK5oBLRpsD2DaANAvZw4M/eOhMen4wvwDdk4YNW7AXK23rYXs/TwK7mn9+DKp8uts3UZfsKHo8CVnkEYqnFzFDZUoPqHE0sPUhVpf44zkdo7WCH9gs9msGUTcGbhse6mWRGM9GHyaWXl9wyP30cZZZ5g439vvwVn0yqnlRSp/GmfV9WqaeIRs75uoJyIMOmmLA79GAQtJ4DXdXATSQ8N3nA2KW+Tp0tfiHldOPjm9lspC7NUt0aJARrx2K2nZojoDG3+pmiyHcmL8cWwwHa8jj3Tip/CF8CH2SCzbBLC3VEi/WxbyAJ+7OF+DsU/aNQT3UWIUg6FJic0gCx2WT8AqFZ2nx2x0q2l2XzFJO18diGhomZm9hZs8r59EWwon8dHN9ECpuIBNORCoQ13qV7PvTJOBcEPTg6P7plNxX5PvujkXW5gU+VPd9gtCkbjjxg+Irzug2TpaKHIsc0yavf58E4/7K8LIElneRx1vB2xZabn5tpW43ZI1/J4GcdmFnLwylYd0tZy4R/PPfGWdhRpTMoZHuB0uM6PWYul+mf2Rywid6y0j/ZcA9guLy2cCBQ0muTGJkzJWmDQ2NnZal4D0EAl0kPHBnLamCXjdzR/zDBXH3JTGIj/eiSKR281VtKGAJg+mRYSxzP8CgM8mhhOCQPBPI3Y6KroSNrtx2djXdv89WLOmRCIZklRYNiA+wg10OEhMYkQikuDrv+j2J7P0IZDuM9HTfTYwI4h7ER6jFm7IXu2gmDNA==,iv:gcIrNJBdB+zQ/zfOclplw8ZQ1g767XstPBGyRV555Uo=,tag:+liaG+fmIUmpSHRBPjEDnQ==,type:str]
sops:
    age:
        - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MUtWbVRBdW10akgxOHo0
            NzB4TW9ZWXk5QUl0NGMxRlJkUXdEa1lFSVdZCmhNUEVPazVXU3Fsc1FKN1BJak9G
            ZHlRZ1ljOEl2UHZtQ2QrcWtlbExMdjgKLS0tIENMMU9kaTNNS1hMRk9yb1V0SmUz
            citGYUUwK2lWOXVWUERjR2kyb2NBZGsKGHDFDcPt7dp1YYbxvshze0Zqb4RqEWLc
            yk3yutdIAQiCZgmslT2zp4qJYosSPF7UIN9oa8DPsrrjfjGXHOjHag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T18:43:14Z"
    mac: ENC[AES256_GCM,data:4gTl1fb97ymkKNCoRc8KgilcXnSqp/0jWx7Ypkq3BSFWCRicw6jhFU8T5Rs82Nvaywyeo1GJp2/ISu6F9/z2+PBYL+wrnrn6//U9X/UeYhWy0snfeYoogsXio0kfoRdGECEQ4MVfoX9gtRtjyb3EpCbc5gaMaPgTO6xb7ELqjTs=,iv:KpoE0gKx51SKAd5RoMsHvJ019gTR6/i6v6AojOMWmio=,tag:w8nq0hW890V8RQYHYGobwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
