apiVersion: v1
kind: Secret
metadata:
    name: adguard-config
    namespace: adguard
stringData:
    AdGuardHome.yaml: ENC[AES256_GCM,data:9FuI91wPItQYYQeLNHc4snO9dxbAKFzqdVuO7d62oMpMFDB0unzb759ARxgWqShZMK9r97OCedUkF4cDKEmmSHbp2BL2zpKT4HjRmEngzS+A0A5Mk6yiuHNHKDYqahUIq1qxvTI2VpuCpFd4U1FpjOgFjbu6ezvV6HxJY5pMk/H9wA84JD9NdU7eW3V2usb6oD+lI1ujDzC64zKZDx2h6BVeEWwNClLlO23lugOBZh4fJfgOwSinacATpHgIu0kxpA2P66dM0pLgHynbYtiE/6cdYYR0W+Q0kmFsqHsUQj0xPPq5ev1Qi8f3d/3Ou+rajeE3AsU5M1pFIFzWGJiJ9fhxBgOstTuJJ8b+ccTbtaf14whLs9hdljEQHW5W6iuwa1nDUrdBJq0jHIo36QNMZZ2AS7Gp2JrnpKH1QthFd2YvyBZ/fb5jd7rjnu+9ijssxGQzWuGW58xIRMinHg0hcakawIhZ6490OCiiNOH7wkymb8dUkpEwKN9AxFuhpST9q/vXxI4fMSXH/dDuq9MqqzqHUxP7zIafT+rfsU8qo4ccgrnmVDLnJh+A/QGBkc/bpOFiVpM73AH8GKbLR8jIDXeByWqTSpVO8lEEfqLRIKwAMmd6mlevoe2kumNnQKNyjKngfOq5ivjGmwcJisLVFM7DFsraL7D5pfVGMayhlsrXKDUEO2UShPKs3xz08Z/RpxCMasj5WdbOgy1VFhrPp46Pc6KYayR3JUVKdMNs7GBIT6eu6tonPD6bOJC3n7m1kZKl1bO5K0gbw4kG9DHpWz1CyGfxcoPPn9/eHK+CKRrQJQ4/glMliW/5hH9/uV2g98ifaniYBYQD/aMGMGnfyrFJXUDFFWbWrE+ukVTaPMl8Tk0PlNs/6kSY1NO8llXhC7lbRFKYIUODUanEzKf+zSSa7+bBe6Sl0+VpqFlKvqolc73XUTsHlqzDd0nWi5VghoEcN1FBEoyvWPTrU/r0lNDS79aEWiOrUzxyAAl82OoDfOqXsBHyy7AgEQ/6oxUgc0s+7SSgJIwDxh0yyN0JpQKPmouu0I6mqu1g3Qa/FnclEGpr9EYWet6MVyOQyc3HekFVl2r9i9wVY6R5bHqV4ShmBnjlYBGHWUIMRjJ8PFJFHxnJK+WcjMyL7qi88U/bYnG4GWwcD5GxgTRiUqTFQWH9PDf4O3BWOnLMbaYF3aiHZWeOHiNIjPjdoWuBbVbUeFzPRsvdn3Lh899lOjw3ZLs/AtVtJjHMIrPt1IlOywkelrqEmkp0wMpq3JH5/pRufY9b01CrfNMxcYElxZcrD0cJ784WTQDp0zteHkt5K9c4LOx+NY8fG/7F6Jgr/Hh2iDMP4lvDuTefIg==,iv:NSnT4ClJJaU7D+WnwVOOjG/8iKL8P8qELpuzwJqFSq0=,tag:kTDay27ol1EGuAavwuYqAQ==,type:str]
sops:
    age:
        - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MUtWbVRBdW10akgxOHo0
            NzB4TW9ZWXk5QUl0NGMxRlJkUXdEa1lFSVdZCmhNUEVPazVXU3Fsc1FKN1BJak9G
            ZHlRZ1ljOEl2UHZtQ2QrcWtlbExMdjgKLS0tIENMMU9kaTNNS1hMRk9yb1V0SmUz
            citGYUUwK2lWOXVWUERjR2kyb2NBZGsKGHDFDcPt7dp1YYbxvshze0Zqb4RqEWLc
            yk3yutdIAQiCZgmslT2zp4qJYosSPF7UIN9oa8DPsrrjfjGXHOjHag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T20:09:59Z"
    mac: ENC[AES256_GCM,data:1VKMZUKGrfa+jTfTKJLtZnVH+XMi8oO1zttvtScfTDi/XRxOLGjqA0VQX1bepPqRwUnUl62IjkcGiDk34/8HY/VVZBMwMusihyte7tonXBTL9kYf3L+jAwtVzwv62dJUk5umVRg966EA2bEcE2WP+MlzbnmFldFdgsMjlctO2qo=,iv:glvXnmQeMXkn6UkEIZ6/RlmxFwILK/VdD7yVzoTHkRY=,tag:2Jak95QiBhBKWumlsiqmdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
