---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard-tls
  namespace: traefik
spec:
  secretName: traefik-dashboard-tls
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - traefik.${CLUSTER_DOMAIN}
  issuerRef:
    name: ${CLUSTER_ISSUER}
    kind: ClusterIssuer
