apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: weave-gitops-tls
  namespace: weave-gitops
spec:
  secretName: weave-gitops-tls
  dnsNames:
    - gitops.${CLUSTER_DOMAIN}
  issuerRef:
    name: ${CLUSTER_ISSUER}
    kind: ClusterIssuer
