apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: weave-gitops
  namespace: weave-gitops
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gitops.${CLUSTER_DOMAIN}`)
      kind: Rule
      services:
        - name: weave-gitops
          port: 9001
  tls:
    secretName: weave-gitops-tls
