apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: weave-gitops
stringData:
    username: ENC[AES256_GCM,data:QI1qQ4s=,iv:YVXkXMV0MneyFPEwWZELxzuh+awZc7IQ1f4kBVodEoM=,tag:g9Qv+yvnfvPmZZw2bHqBYQ==,type:str]
    password: ENC[AES256_GCM,data:dmz26xNUGNSGGMqRHXjI/mE246YQzgPpmgtT0XJf0/5lEKPPi2ikAc8GZqHcEeXFHLF6mav+VyMsZZdJ,iv:EXuFHDojdFb+ACvZyozBbxjqUUWZWeHMaKI1HX9hEf8=,tag:/XfWYK+I6ZM64MmihiYX3g==,type:str]
sops:
    age:
        - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdnNPczBlaVBuMUhTdSt4
            N0czaEF0dk9LN2RkQU96M0lXRitubFRIWEdnCmRSc1QxLzRNMG8zeVZjcW9qcnBS
            bWVwN2Vua052L2JxMXJQV2wycERwc0UKLS0tIC91cUswYXliUnA5SGR2RTUwT3B3
            RHk5akt2WFduVFhVODlSbnc3eGhVb3MKxTyxH0B3n8y+t0seiNCGvIWTv+42Jto2
            SsFtoEQIC4JYnjbWdoFW0oImW6eG45zF9mMu6DGY6LokN73BVbhRyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T19:09:34Z"
    mac: ENC[AES256_GCM,data:uUce120W6fKLvKRR4jp4qoBGZlci+9YUS3+as2bK4VYEGVpY7Bicxw3xBXJbuE6ThvN9Vt5ewaYkqFRkIUixqSerxfcbzeIo6Ry3JqlFetHEzkClWIgZHfN8W/fcbO3CsTy4qwfLIduci/ZshgUXk/3vorx8pddWkxjzCxod03o=,iv:ojx6PpIxSQ2QOej8p8CUBvUGncxSBia7AZPAvyJ1QO4=,tag:w1X/IkeZnBLXrbJfbgAJtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
