apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capacitor-tls
  namespace: flux-system
spec:
  secretName: capacitor-tls
  dnsNames:
    - flux.${CLUSTER_DOMAIN}
  issuerRef:
    name: ${CLUSTER_ISSUER}
    kind: ClusterIssuer
