apiVersion: v1
kind: Secret
metadata:
    name: capacitor-next
    namespace: flux-system
stringData:
    LICENSE_KEY: ENC[AES256_GCM,data:0tLL0dr4qKqkeg8A4G4Egdi418l0T784vBSV,iv:F/YtDPdtnXlipg012adTSLbLFIU9fvsPI38lxTHLLCE=,tag:dVolqFiPzyS2lDUy0D7XWA==,type:str]
    SESSION_HASH_KEY: ENC[AES256_GCM,data:j9Hx7uaXCZ7UXFGmxrC2CT+k1+Hb+U1+odied04KmgZ8A6Wfd4nrgZckJqJFvmnY1DrM,iv:eTmZu8tqtKRiYii1VkRlIaJgdytqZDCdZowMG7/a4Kk=,tag:x1ClV4jQlczJjwI2Fki1wg==,type:str]
    SESSION_BLOCK_KEY: ENC[AES256_GCM,data:FZ9SYeIsgXWHaL2lSQqNRVLkxlzJMD6WroP4wgRJdz1QQXKadVMixb86TzKsARuSJ3ge,iv:mj3c1n3FnTNwpYWCuTErrposYJLIzVXKUg14whYbIYE=,tag:jY23Op1X+ozeHdWuTLK7/w==,type:str]
    registry.yaml: ENC[AES256_GCM,data:Rl+mJfWKlIjBYCnzavSLalA7nDs0f4zGxr/OalkH9XoIJpf2PIJgMrDC4k2E8Z9U06jpsztnaxAJvJEKGQUn3rar1GPVnwb53i8u8FbYl8rnQEz3CzYGJT5bMyFSm9/bej3KazLSfzh08779czb5XAlRX4F15oFULG7BxJ0H/8h4JiIuMzWffwbWBy6s0AuMnelOLraLvL/xWld8ohsFcHAii4wytMBPE00Pur6ygkVO2JRS4ae3BshEKyeqhdShp4HzIrE4ZCi/3mn2tTtQOhfIZRMf1EzY/7D8QmtFo3Y+Byu+33+/l/un2KpC+LRQgECdXKdJpdbIeeQsHkH8npPHKmg=,iv:1TmSOwVVEX/MZbguuth6XuRppWSHkoYIXAX25sdjtbc=,tag:GG2Km8sAttDGdTKsc1xDag==,type:str]
sops:
    age:
        - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSEJPVUpOeHlGTHREUmp6
            T2s1TjF0b3Q3K09ncjkxMjN0aHVLanVFNjFFCmx2VFpHeHpNZlJNbzlxRmc4TU43
            M1hsdWtLVkh5OGRTZWwweDVoeFJEMVEKLS0tIEhUZ0V2SFFhclVMeGxHR3pWVkl4
            aFBjRUpkZE1QcVVHOGs0Z1ZFS3JRRlkKG1xtzuZCXf329SwVm5qXAIrKXNOIuDhf
            ztrIirYSTQElOlBjtQPRF9gAzYmfmJcufg+kBGPqIUZJhlWMhtpvbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T19:47:05Z"
    mac: ENC[AES256_GCM,data:ik51HPsKYWo/H1Cq0/mVAHLkyDSPpuzbH3xxcT2fIFvLF5ROrMnBdTgArbQkQNYchaPm2zqRDTS0Ik7R2DLYMk1ci6fEWnSqZqWwB9moPbFKE3EoY7/xBA0dgkl8bk0a/wt8b6JurtKB1m3zEf53aGsI9Cd35LeypDGWf4SCPSU=,iv:AzHwzguW5lXCXueb8Z3BMMhFILMaLr0p5zBrsGkuUYw=,tag:OIXQNhb29aBBcQOhc4urZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
