apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  #ENC[AES256_GCM,data:N1QoJlh/Zye2YsFbE6cU+sPIBj34dQGOb4PIamkfXQ==,iv:x+jqluD21nAqDebjlQbVqm7iEACT2oD+B2Kc75upo8k=,tag:Gzf+2kjKSMkBx+lqaDqb1Q==,type:comment]
  #ENC[AES256_GCM,data:2897BgRFDE6Bzt1o3OjtPtv4fqC5JUzcVu53e4jOIvuPfHpvwyCrE46+cJ7jsCMEutYvbqk4,iv:RjT5Vz0LH6BWOSzwQCqqFYfB3SdiNcwekIBMEcwlZP0=,tag:46CRhSWxXdwITw70nJrApw==,type:comment]
  SECRET_PLACEHOLDER: ENC[AES256_GCM,data:zkqeDbsMtM8YITc4rP83qgk7ucGkOYlkvtPA,iv:kGzdhoWkyeSU7pcujOGeU0ZfSe5XU0OaeOEJtobYS2M=,tag:4SH4rfg0jvdunaZKslxe2Q==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZkNjd3QrQ09vdWhoWnVD
        STY5VWxDdlVsaFhscnR1OHh6NGRKdndYRzE4CldOL1luMHQxa25uQ1lZS0I2Q0ZX
        emp1Ynp0cENpRmR1UEdIS2xyZXM3OTQKLS0tIEJLR0FOWEVDODd2bVJFWjZpR2py
        RllvZ1VqeWQ3SWwwWWpKQ0xzcFFaRlUKekN9tZI/FxyNLhQZMZH36pqN02IREVv9
        rcwsLO/g190Z6P4gnvEbUnZYa9V+56TlJ5Q63zVXkudFn1c2Ainzdw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-13T10:52:03Z"
  mac: ENC[AES256_GCM,data:3KH+GDDi3Rza4EVOAkPe64CioYXUCzCy4opf4wI9ONh1sBXjM/OYe6R98TEeJD8yZM7jUSY2io+Du/A6tWfTzArY6IRdT44B6NqXZN8t5L6gimur4mfHWMPnXWev9npATooXFOPhwOvY5bcyJzpF3/5Cyd4J9MVYZ5N52gE99wQ=,iv:s21nZvCFtjrnhWDHzc8BRlEDUMkYVyE1FMknv+NYsp4=,tag:ZrUU/5SGvJ95+4cGv6UFSQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
