apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_PLACEHOLDER: ENC[AES256_GCM,data:TVq+JmV93Rz0Ew3QX57K9nIHQGseEB+bznKx,iv:XF4H7cfv2jpOKAHm8egFrNDdwNjBSa3YLDuws24Uia4=,tag:nDUK1DkBf3IAm5suicbsbA==,type:str]
  GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8rdI9+Yrhr2PY8pW0KAYkETgfXwdV2Ps6BGIMeMQrec=,iv:K8hOH/FMevSLJ4uK2Nr8DoO44F/KVujoogpbQuCZdSY=,tag:WzEV6dHB2RQ7fkmS4uuNQQ==,type:str]
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:48G0B1CSW81T7gff6bqSS+ZZ82lzQ+f7POueORwyadGE21KSE/mWO1TrKs7JyfNB5jRRIsFnJH0gSteyNeB3lKaWm5ZafIw79iDld8On4b1umRhX8FzDsJHNFV+Ts2JVUbYJjP7DtfacpOWJra+Wm2uqYF0h9BZjqQ==,iv:gAnvmZQA6yaontYlB38F90jPEjKPlXHpJdVxBz3titc=,tag:meUAFa8RVW2wCHiFzybhUQ==,type:str]
  FRIGATE_CAM1_PASSWORD: ENC[AES256_GCM,data:PQrglhHpk7TdcOzqkZs6,iv:1vxp2Ai30MRRBdEgFHRK88mOwwmKm3EhHs8ym5ji64c=,tag:V1KXg8yMuGvg6VHpvmcjsw==,type:str]
  FRIGATE_CAM2_PASSWORD: ENC[AES256_GCM,data:9oJjE2RuV/14SqPVoCyG,iv:nhztEJX7QjlU1UTxLBpDA7KruIyH7kamykNqnHi73ws=,tag:fw1BFiflbmZS5dRghuCfow==,type:str]
  HA_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:w4GAy4wegx0LHXOOjJQn2aKtp73rJGKVHU78BYFJixU3eUmprd+BEIHkBg==,iv:yXodn5J3eo7zq8MW/M28TLlo4F9zWl3QivewmVsE5sc=,tag:Rm9l2Efh0F4y0zgeG+fbdA==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDK1BrN2NDS2EzK0Z0Qmhw
        dkJZT1p2ZUxidmFPSi94TitSTlkwdHVMd0VJCkJnMUlsTnVsbG95dUdQRnJWVWhN
        eDhhQ3AvSituWTNWWUUvNWNUQldzZEUKLS0tIDgyS0h3YVdzNEsrWjh6U05PNSt6
        dElRNERDZFU1cUxUazY1RktqQ0tlb1kKTDWUPNK2o6MSvzW+4Cv29RjLj/G7NysZ
        dEI+BWCvD4WKqLLRBTZ4fEVsoC+oPreqbjIXsVbVotxONpciJiYPkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T19:51:10Z"
  mac: ENC[AES256_GCM,data:cdhlRAI2gG5WuZobRHXMn2t8n3c4kApIUBVjcsk1xwlnhD/ZJN1vi15zPTcePXrxG6MVA2wxmP4ghm/LlhZQP2c6x87FjHWo1EjWKc/U/ahbtvK8ZuSW9ldYGUyExgVr2n4nnXZ3tkmOrs6GnWEJ7xuG+OmbHuONwnZeltG/RKM=,iv:ermK74B9BfcY9MHg/mty5rn50+8VgUDI71KbNAW1GeY=,tag:tZ/RZYzGt0vuWI1AQBNgMg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
