apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_PLACEHOLDER: ENC[AES256_GCM,data:ag2S6igrkXJpUXMswlquis/xvA3YvoJkNs2N,iv:RmK2fLbDNJlKC0mk12RnVBl97HGiXK2q9tvbT3uHiXc=,tag:o7zSNeboA8lAfYPHtxhxPw==,type:str]
  GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:cLBD112P5HPr1Zx4BNkX/x70Mrl7jDuSa5f4q2XKn1A=,iv:R6h2As5ukJ15qAuCV/gEeTxCygXw3hBbFUiuRAkFMBA=,tag:m6BFzz/zuscUZoCRgiyCFg==,type:str]
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:O4AbZg8xDWw+yQ2LKiwAglVAirZAueKfhwrlAPn+9EoqoC9WyFfS1yVYXq/kEcL6maO9WHfLvR3to7TnEM0xkvXENZuY4tz+Pj1U7Epu6jPoaM8E1A56WfLr8YGLGLhA7waWVai9R8WGgZgOwMhMqG1+eAmQRU3rUg==,iv:h/x2Ym6dmHgG/FY5i25IIa7EnN3JnoGm3ZxruaXSHsY=,tag:Kufp2oubBKvYZ2CJIyVcDA==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSUJjWER0Uy8zZklrNXQz
        cFpwaW8yWnArRnUxSkl4a0ErUldOQVBBZ0JNCjhsWE1ZamhLbHI5c1d5Z1pBSDZ4
        dGloRGRVNU5uQlc4bm1uRDNHVkxabk0KLS0tIFJxQUIzVDFNOGczcWRzT3JPcmd5
        NExJRmNSSGkwUWpwNDduRnVYc0hjUE0KSBwUlxdbz1Ucf7fzKTU0YzhlwVKmClcR
        3787CuZsuVwdzb5TAmDcMlp9H+U8ROsOh1T5MCXuE14WothM575rDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T21:01:23Z"
  mac: ENC[AES256_GCM,data:khXHc08QL2JD0A7fr975NHo2ToTD0x5ZxKuIqso8OtUvwjcShSNkMibqgJuKf9gvrcrABG8P2q/+SfI6lwH7lHjBTRztSs7130I7W/f5hW2UPfL0INqWbId+A+Kk1yD8CESgIRoe4bd2jx/dDD7nAJOhRMUmrLcAT/ECO4cIR1c=,iv:fNvJUO1TtSGIX9GAWs0WPHPLp57cBGBO/kceTAJWCvY=,tag:8yF/ZpAbhbzYSbYp11atfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
