---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_DOMAIN: "home.arpa"
  TIMEZONE: "Europe/Paris"
  DEFAULT_STORAGE_CLASS: "longhorn"
  CLUSTER_NAME: "going-merry"
  CLUSTER_VIP: "192.168.1.9"
  NODE_LUFFY: "192.168.1.10"
  NODE_ZORO: "192.168.1.11"
  NODE_NAMI: "192.168.1.12"
  LB_TRAEFIK: "192.168.1.4"
  LB_ADGUARD: "192.168.1.5"
  LB_POOL_START: "192.168.1.4"
  LB_POOL_END: "192.168.1.8"
  CLUSTER_ISSUER: "mugiwara-ca-issuer"
