apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_PLACEHOLDER: ENC[AES256_GCM,data:5Zlp5WWsY2OPmh8hywMQ8h2jtEfV/L7y7G77,iv:fDefjhuwAq3iMpKk/O+qZKzoCACJCGMyZgyD+JoQWhM=,tag:xyCJSZBaGepEWqO03CYdWA==,type:str]
  GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:KLNJOlnnP+RxWEpEsAz+3JVLZV9J+bG4PJeQSvVGxM0=,iv:YyJ1DJIpJZMpICDVfCzOYExuRUFfmepQ+F43n217UFo=,tag:vLGKF4Kg0baLO9XsASZLxA==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrR1o0QzNwTkFTOW5LWFNG
        UGFUYmxsRTVsdzNCWURJenBKMlFPMWR0UHdnCnBJaHQxeS9RSGdMR0lyNisxRHNM
        UmIwR1hSV0JqaS8vc2lLeEI5aVN5d1kKLS0tIEhtc0lBL242ZFdEUGhQVTNOMzcr
        VVM4SzkzWUV2aHdsdjRVYlRRSnJra1UKVOKe925P8gznceubbCa9vAK9RzH4MYqo
        5l891bQFGHBPKtrvYeeUkJ0AHw42G0KHpXIGuk+36VqVxjsqOrmQ6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T15:23:21Z"
  mac: ENC[AES256_GCM,data:X0VKzibrzeQl92YWPln2c610yOVdl6++p7j9wU4sFfDCiVp14gX/w2qA00gS7aPQP/cod+Fe/1kJ6fzCFtr/eGzrsfatf/EQ4PWgt5+YJ4BbXW1jdVDBP2Mip4F7G/SexmButMVRc1La0v4GPODdik6Mk36gs0IVlCspmBE7z7U=,iv:WziejuLUda9Hpt6RJaPOJzhIZ+skFGxCnN7z6X3flyw=,tag:tsdYBfS1SaxYyJVWBNrnFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
