apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_PLACEHOLDER: ENC[AES256_GCM,data:TVq+JmV93Rz0Ew3QX57K9nIHQGseEB+bznKx,iv:XF4H7cfv2jpOKAHm8egFrNDdwNjBSa3YLDuws24Uia4=,tag:nDUK1DkBf3IAm5suicbsbA==,type:str]
  GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8rdI9+Yrhr2PY8pW0KAYkETgfXwdV2Ps6BGIMeMQrec=,iv:K8hOH/FMevSLJ4uK2Nr8DoO44F/KVujoogpbQuCZdSY=,tag:WzEV6dHB2RQ7fkmS4uuNQQ==,type:str]
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:48G0B1CSW81T7gff6bqSS+ZZ82lzQ+f7POueORwyadGE21KSE/mWO1TrKs7JyfNB5jRRIsFnJH0gSteyNeB3lKaWm5ZafIw79iDld8On4b1umRhX8FzDsJHNFV+Ts2JVUbYJjP7DtfacpOWJra+Wm2uqYF0h9BZjqQ==,iv:gAnvmZQA6yaontYlB38F90jPEjKPlXHpJdVxBz3titc=,tag:meUAFa8RVW2wCHiFzybhUQ==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDK1BrN2NDS2EzK0Z0Qmhw
        dkJZT1p2ZUxidmFPSi94TitSTlkwdHVMd0VJCkJnMUlsTnVsbG95dUdQRnJWVWhN
        eDhhQ3AvSituWTNWWUUvNWNUQldzZEUKLS0tIDgyS0h3YVdzNEsrWjh6U05PNSt6
        dElRNERDZFU1cUxUazY1RktqQ0tlb1kKTDWUPNK2o6MSvzW+4Cv29RjLj/G7NysZ
        dEI+BWCvD4WKqLLRBTZ4fEVsoC+oPreqbjIXsVbVotxONpciJiYPkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T22:43:25Z"
  mac: ENC[AES256_GCM,data:a65MmcRcBz1JaC+IasUTblvGU+GspUvu9eIfSC23QUIIflo7OBjUi/QjLoiYID3+nVWW6PKAqqaCnycL7TK0ALxqbgEtzOwO/7e6kmnUFv1ZS2rwEm1IlcZvA34pI8YUxu3q4NdCNlZzNiQ/FferZqC+dLeihqvsNNRJSKNpraA=,iv:K0twYBfQcrrAVS1C7bJZn97G4DQkcsnb16UtpqKJMr0=,tag:Lw6sYrN7EtURyss3tbcehA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
