---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-hubble-ui-ingress
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: hubble-ui
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 192.168.1.0/24
        - ipBlock:
            cidr: 10.244.0.0/16
      ports:
        - protocol: TCP
          port: 8081
