apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-discord
  namespace: monitoring
stringData:
  webhook-url: ENC[AES256_GCM,data:QwYG87syisWUklFIlm7mHRUMrUTcJmR2uycY50vMQ5ZsFEZjvwfebt+0yKKXAYLHHhrRsu0TkmDxn8bMmpBDZagbMBbgap7Ah2W7pnAoedTP0UMpbbhgZ7ZT8lFCCzLSLbwItUBSlAI82mm25D1e7D3DmlJawpC9ww==,iv:vsT3Rd4D0rjs9oNfogEFb0+lO4YZF3pvh/Ut/JNyQX0=,tag:QUE70XGdH/dFgXfftNDU6Q==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdzMrQ29GamdMSDF1dFJq
        YmlRTDljemwvOWpqcnhwcTF3WXRzQWhlOTNZCnJXck1FV1N4MXJCb1ltMytZc2t4
        L3VPU3diRmVSVjN5YTJicEpYdzJONzQKLS0tIGtMb2V6TTYzdVlDUjh0OVF6M0VN
        UEtWVVdFNEhtcXlVcHlUWTVTbUwzZWcKfR9kSwhBZ1SyKngDHRj9NI8HRGubHwx4
        aXjKvBFsAWDu6osl/XtG6AammRgIa+ClHJ5V9ETbEz7pOjoUb/wpig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T00:29:57Z"
  mac: ENC[AES256_GCM,data:KqIhe5R+EVVD5uHyDUsmCu5q6jWOqiC1tUyGVavJNZR71V8F2VxBOMCE2VKtC+K3lnZkrWW6344oaJemGX/3xFgc+BQU4Plv7dbCGovCwdDc+AzZyDuIOY0BbsqMYR6DxmFsYo9vaNVCDzeyCQgWTSDh5w0vP9uvU0HAiE7fruU=,iv:FcokWS2tW7uUoAlhLHwhUH6UxewsS+64TFd+hHFzxEU=,tag:Ol0OV+bqHQ3fyAhiSNn6Tw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
