apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth
  namespace: monitoring
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:ZtDQkqdUjrMJky9aWg/8cdiZJ+eUKeYAG5xwgVH6Ff8=,iv:Tm4aSIQOZH6kKQI+3NgmOk0Jxfm5xVMZ9LjHF8H9jsE=,tag:/WKJyaNVzGRmtb1WfcbeDw==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVURFR203ajQzVkVEbmdv
        UHNTK3p3eitJOWl1b0Z1ZWFreXVqRm5UK0NNCnBsaWdvRWVJN2R5RkRpTHovWm9q
        QlVlSDZpOTlRb0RNUE5XeFI0VFl4QnMKLS0tIEN0V2hlL1JRWFh2UTdZeFZVUTZn
        RDk2S1NTaEtqRUpxVCtoekRuRDhUbzQKrwIPJK8caIpBN8vxLPKCzOBulAawXivw
        13ZIpZPxCtrI9u1PyyPSY8axLzBdyLtAgMqrQXsYTeht++tWsjY7fA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T15:32:02Z"
  mac: ENC[AES256_GCM,data:RjjD09srXzxuC9ZS+Kl3+m0gomDiroP1GNwm4CHaxxuc6bStRkRx7uw1Szy9VWvBx8MNcf0p+EP/IuYYvGcEPtyQCDUP0fWEkWxKRLJnViaF6bAuVlBKOUr3autNMCdjKQnxOfU5qMhs6OGnutrL0xs207KsK6X8oMyAv/5qHoY=,iv:JRvk2XTwo5AajtQtpPJu4FKsxNf0aNfk+1Uh/rLYxio=,tag:n/68veVFROC8DTTwdfwTAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
