apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
stringData:
  admin-user: ENC[AES256_GCM,data:XDn5WgA=,iv:JmI/PoMEk+1Ic5QMFCttAsIXPZRO8+gPd3yXTBKNBBs=,tag:+vXvk2dWq07ylTKgyj4ItQ==,type:str]
  admin-password: ENC[AES256_GCM,data:NHqDQd8zUGmbWjI930J1c4g+DA==,iv:Ip6aY8r1WVf5MuJ3lkr9sPCZPzSp0W83UzM995J7XHY=,tag:3aRU5Tpw86JYBF5Atu3/TQ==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkL2M3NlRNYlpTZSt4b3dK
        SmVPVDRIV25IamNKd05QbGoyeFUzNmxEdFRRCjBUMGJjanUwb2F6M1BEQmhGUXpY
        SFY2L0Nyb01IMEFES0QwcDloYytYNzQKLS0tIEE3dGxZalFwRW5PNU1meG5JampQ
        NGgwUGdCU2tseWx1OGx2MkJqcEZaQkEKXV7M+Mwvtz2fIov3B0mji3p/+hyuU7fj
        uOiKjiyVyyNVnEvULSWAmVE/jKyrYfsYkyDh3QwiLXHgcgTjpRXtSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-12T20:21:25Z"
  mac: ENC[AES256_GCM,data:vMt9a09MiR3LI4LZA+LzqMMiml9y29B18WuofoOEHQH4jU4H+OpOAW/Z0oh40qyWpln2QLlpA/wVMDtNgv5vfvtKgi5Qj+2KEm6NzSeceNkcorzu5K2jUNHq+CUP+W7gLUe1Nn3rbLwCUoqQGrTBX1U5Wz4tZogR90W0los/t9s=,iv:7SR+ZP/bm8+WqgT4XvAY5WPHEEbIMZVCprzkXDOLTnQ=,tag:wYeVFt0HJN4HkYIiqp3unQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
