apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth
  namespace: monitoring
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:ZmpkoMmtpqW3Mrbpea13baIrSH3Vt36x7OJgPFfhBVU=,iv:mRGkInOiZqetsI8TZYnt/sqp3heu4SuL0ybwYkS6PCs=,tag:MHhdmqUth67yZykUL5eSng==,type:str]
sops:
  age:
    - recipient: age19l6qdztn2ff797tdlsekuaycgq2gdgt49tp490cpsz8mgd9f6s9s4xf0yl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dktJSmVmOXcrWjZpU1Qr
        anNtSEZNVmc5MG5OVzQrVVQ5bWVWc3luWGxRCjA5MGx4MkRTczltNVBrUUJrb014
        Z1V4ZDBzREc3S0taazM3OW9QK2xRY1EKLS0tIDczQkJyVDF3UWZLQTdzV3BHU2Nx
        QTFBdlRRT3dOYXg0UDY1dEhob1p5dEkKGI/Ga/r3RY0IUx2gXLafzPiHB5UcDx6R
        5KoHYfbzPXZdfJmXddlyM5OXYyaYRPeRw8PCpetKtw4g2bYyRVtN8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T22:42:49Z"
  mac: ENC[AES256_GCM,data:JLf7+IZBovOtkuH+ieBSV4yeCP4J9LKGkkg15UiVkHirROrs4w66IRM7wXdDSR/fZz2VJMmzXKl3xzDwl1dfbaZ6fHRq7TQhzQULV7uRJn6fXmREVXqtOMoCeERnnRWseKQQb/DrRZKnemNoNGrlCa4peD19mod9QhD/yeg2Gns=,iv:M6TCXh8jxR39sEY8wxg1EIn+HFkE2pbOeUb21fuGuTg=,tag:9Qb/43H7bRUfNgW2rxhjqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
