apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - grafana-secret.sops.yaml
  - grafana-oauth-secret.sops.yaml
  - alertmanager-discord.sops.yaml
  - helmrelease.yaml
